buku/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path("", ListBukuView.as_view(), name="daftar-buku"),
    path("rekomendasi", RekomendasiBukuView.as_view(), name="rekomendasi-buku"),
    path("ratting", RattingBukuView.as_view(), name="ratting-buku"),
    path("search", SearchBukuView.as_view(),name="search-buku"),
    path('buku/<slug:slug>/', DetailBukuView.as_view(), name='detail-buku'),
]

rekomendasi_buku/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("buku.urls")),
]

buku/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
from django.db import models
from ckeditor.fields import RichTextField

class Buku(models.Model):
    id = models.AutoField(primary_key=True)
    judul = models.CharField(max_length=100)
    anak_judul = models.CharField(max_length=100, null = True, blank = True)
    sinopsis = RichTextField()
    pengarang = models.CharField(max_length=100)
    tahun = models.IntegerField()
    edisi = models.IntegerField()
    penerbit = models.CharField(max_length=100)
    tempat_terbit = models.CharField(max_length=100)
    topik = models.CharField(max_length=50)
    isbn = models.CharField(max_length=20)
    RATINGS = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    
    rating_goodreads = models.FloatField(choices = RATINGS)
    rekomended = models.BooleanField(null=True, blank = True)
    slug = models.SlugField(default="", null=False)
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.judul)
        super().save(*args, **kwargs)


    def __str__(self):
        return self.judul
    class Meta:
        verbose_name_plural = "Data Buku"

class GambarBuku(models.Model):
    buku = models.OneToOneField('Buku', on_delete=models.CASCADE, related_name='gambar')
    gambar = models.ImageField(upload_to='static/img/covers/')

    def __str__(self):
        return f"Gambar {self.buku.judul}"
    class Meta: 
        verbose_name_plural = "Gambar Buku"

buku/views.py
from typing import Any
from django.db.models.query import QuerySet
from .models import Buku

from django.views.generic import ListView, DetailView
# Create your views here.
class ListBukuView(ListView) :
    model = Buku
    template_name = "list_buku.html"
    context_object_name = 'daftar_buku'

class DetailBukuView(DetailView):
    model = Buku
    template_name = 'detail_buku.html'
    context_object_name = 'buku'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
class RekomendasiBukuView(ListView):
    model = Buku
    template_name = "rekomendasi_buku.html"
    context_object_name = 'daftar_buku'
class RattingBukuView(ListView):
    model = Buku
    template_name = "ratting_buku.html"
    context_object_name = 'daftar_buku'
    queryset = Buku.objects.filter(rating_goodreads__gte=4).order_by('-rating_goodreads')
    
class SearchBukuView(ListView):
    template_name = 'list_buku.html'
    model = Buku
    context_object_name ="daftar_buku"
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Buku.objects.filter(judul__contains=query)
        print(object_list)
        return object_list

buku/templates/detail_buku.html
{% extends "_base.html" %} {% block content %}
<section
  class="flex flex-col items-center justify-center gap-6 p-10 md:flex-row md:items-start"
>
  <img
    class="h-1/5 w-1/5 object-cover"
    src="{{buku.gambar.gambar.url}}"
    alt="Sampul buku"
  />
  <div class="relative w-full max-w-xl overflow-x-auto shadow-md sm:rounded-lg">
    <table
      class="w-full text-left text-sm text-gray-500 rtl:text-right dark:text-gray-400"
    >
      <thead
        class="bg-gray-50 text-xs uppercase text-gray-700 dark:bg-gray-700 dark:text-gray-400"
      >
        <tr>
          <th scope="col" class="px-6 py-3 text-center text-[15px]" colspan="4">
            {{ buku.judul }} {% if buku.anak_judul %}:
            {{buku.anak_judul}}{%endif %}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          class="border-b odd:bg-white even:bg-gray-50 dark:border-gray-700 odd:dark:bg-gray-900 even:dark:bg-gray-800"
        >
          <th
            scope="row"
            class="whitespace-nowrap px-6 py-4 font-bold text-gray-900 dark:text-white"
          >
            Pengarang
          </th>
          <td class="px-6 py-4">{{buku.pengarang}}</td>
          <th
            scope="row"
            class="whitespace-nowrap px-6 py-4 font-bold text-gray-900 dark:text-white"
          >
            Tempat Terbit
          </th>
          <td class="px-6 py-4">{{buku.tempat_terbit}}</td>
        </tr>

        <tr
          class="border-b odd:bg-white even:bg-gray-50 dark:border-gray-700 odd:dark:bg-gray-900 even:dark:bg-gray-800"
        >
          <th
            scope="row"
            class="whitespace-nowrap px-6 py-4 font-bold text-gray-900 dark:text-white"
          >
            Tahun
          </th>
          <td class="px-6 py-4">{{buku.tahun}}</td>
          <th
            scope="row"
            class="whitespace-nowrap px-6 py-4 font-bold text-gray-900 dark:text-white"
          >
            Topik
          </th>
          <td class="px-6 py-4">{{buku.topik}}</td>
        </tr>
        <tr
          class="border-b odd:bg-white even:bg-gray-50 dark:border-gray-700 odd:dark:bg-gray-900 even:dark:bg-gray-800"
        >
          <th
            scope="row"
            class="whitespace-nowrap px-6 py-4 font-bold text-gray-900 dark:text-white"
          >
            Edisi
          </th>
          <td class="px-6 py-4">{{buku.edisi}}</td>
          <th
            scope="row"
            class="whitespace-nowrap px-6 py-4 font-bold text-gray-900 dark:text-white"
          >
            ISBN
          </th>
          <td class="px-6 py-4">{{buku.isbn}}</td>
        </tr>

        <tr
          class="border-b odd:bg-white even:bg-gray-50 dark:border-gray-700 odd:dark:bg-gray-900 even:dark:bg-gray-800"
        >
          <th
            scope="row"
            class="whitespace-nowrap px-6 py-4 font-bold text-gray-900 dark:text-white"
          >
            Penerbit
          </th>
          <td class="px-6 py-4">{{buku.penerbit}}</td>
          <th
            scope="row"
            class="whitespace-nowrap px-6 py-4 font-bold text-gray-900 dark:text-white"
          >
            Ratting
          </th>
          <td class="px-6 py-4">
            {% for _ in "x"|ljust:buku.rating_goodreads %} ⭐<!-- Simbol bintang unicode (☆) -->
            {% endfor %} ({{ buku.get_rating_goodreads_display }}/5)
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</section>
<section id="sinopsis" class="px-4 md:px-28 md:py-24">
  <h2 class="text-2xl font-semibold text-gray-900 dark:text-gray-300">
    Sinopsis
  </h2>
  <div class="text-justify text-gray-700 dark:text-gray-400">
    {{buku.sinopsis|safe}}
  </div>
</section>

{% endblock content %}

buku/templates/list_buku.html
{% extends "_base.html" %} {% load static %} {% block title %}Daftar Bukus{% endblock title %} {% block content %}
{% include "search.html" %}
<section class="grid grid-cols-1 lg:grid-cols-3  gap-4 justify-center items-center">
  {% for buku in daftar_buku %}
  <a href="{% url "detail-buku" slug=buku.slug %}" class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
    <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" width="100" height="384" src="{{buku.gambar.gambar.url}}" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{buku.judul|truncatechars:30}} - <span class="text-gray-600 text-lg">{{buku.pengarang}}</span></h5>
        <div class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{buku.sinopsis|safe|truncatechars:70}}</div>
        
          <div class="flex items-center space-x-1 rtl:space-x-reverse">
            {% for i in "12345" %}
            {% if forloop.counter <= buku.rating_goodreads %}
                <svg class="w-4  text-yellow-300 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
            {% else %}
                <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
            {% endif %}
        {% endfor %}
          </div>
    </div>
</a>


 
  {% empty %}
  <li>Tidak ada buku yang tersedia.</li>
  {% endfor %}
</section>
{% endblock content %}

buku/templates/ratting_buku.html
{% extends "_base.html" %} {% load static %} {% block title %}Daftar
Bukus{%endblock title %} {% block content %}

<section
  class="grid grid-cols-1 items-center justify-center gap-4 lg:grid-cols-3"
>
  {% for buku in daftar_buku %} {% if buku.rating_goodreads >= 4 %}
  <a href="{% url "detail-buku" slug=buku.slug %}" class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
    <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" width="100" height="384" src="{{buku.gambar.gambar.url}}" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{buku.judul|truncatechars:30}} - <span class="text-gray-600 text-lg">{{buku.pengarang}}</span></h5>
        <div class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{buku.sinopsis|safe|truncatechars:70}}</div>
        
          <div class="flex items-center space-x-1 rtl:space-x-reverse">
            {% for i in "12345" %}
            {% if forloop.counter <= buku.rating_goodreads %}
                <svg class="w-4  text-yellow-300 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
            {% else %}
                <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
            {% endif %}
        {% endfor %}
          </div>
    </div>
</a>


  {% endif %} {% empty %}
  <li>Tidak ada buku yang tersedia.</li>
  {% endfor %}
</section>
{% endblock content %}

buku/templates/rekomendasi_buku.html
{% extends "_base.html" %} {% load static %} {% block title %}Daftar
Bukus{%endblock title %} {% block content %}
<h1>Daftar Buku</h1>
<section
  class="grid grid-cols-1 items-center justify-center gap-4 lg:grid-cols-3"
>
  {% for buku in daftar_buku %} {% if buku.rekomended %}
  <a href="{% url "detail-buku" slug=buku.slug %}" class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
    <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" width="100" height="384" src="{{buku.gambar.gambar.url}}" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{buku.judul|truncatechars:30}} - <span class="text-gray-600 text-lg">{{buku.pengarang}}</span></h5>
        <div class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{buku.sinopsis|safe|truncatechars:70}}</div>
        
          <div class="flex items-center space-x-1 rtl:space-x-reverse">
            {% for i in "12345" %}
            {% if forloop.counter <= buku.rating_goodreads %}
                <svg class="w-4  text-yellow-300 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
            {% else %}
                <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
            {% endif %}
        {% endfor %}
          </div>
    </div>
</a>

  {% endif %} {% empty %}
  <li>Tidak ada buku yang tersedia.</li>
  {% endfor %}
</section>
{% endblock content %}

templates/_base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link
      rel="shortcut icon"
      href="{% static 'img/favicon.png' %} type='image/png'"
    />
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}" />
    
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.3/dist/cdn.min.js"
    ></script>
  </head>
  <body class="min-h-screen dark:bg-gray-900 dark:text-white">
    {% include "navbar.html" %}
    <main class="m-auto min-h-screen max-w-screen-xl pb-20">
      {% block content %}{% endblock content %}
    </main>
    {% include "footer.html" %}
  </body>
</html>

templates/footer.html
<footer
  class="dark flex w-full justify-center border-t py-4 dark:bg-gray-800"
  x-data="{ darkMode: false }"
  x-init="darkMode = localStorage.getItem('darkMode') === 'true'; document.documentElement.classList.toggle('dark', darkMode)"
>
  <label class="relative inline-flex cursor-pointer items-center">
    <input
      type="checkbox"
      class="peer sr-only"
      x-model="darkMode"
      @change="toogleDarkMode"
    />
    <div
      class="peer h-6 w-11 rounded-full bg-gray-200 after:absolute after:start-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rtl:peer-checked:after:-translate-x-full dark:border-gray-600 dark:bg-gray-700 dark:peer-focus:ring-blue-800"
    ></div>
    <span
      :class="darkMode?'text-slate-300' : 'text-slate-900'"
      class="ms-3 text-sm font-medium"
      x-text="darkMode ? 'Light Mode' : 'Dark Mode'"
    ></span>
  </label>
</footer>
<script>
  function toogleDarkMode() {
    localStorage.setItem("darkMode", this.darkMode);

    document.documentElement.classList.toggle("dark", this.darkMode);
  }
</script>

templates/navbar.html
{% load static %}
<nav
  x-data="{show:false}"
  @click.outside="document.querySelector('.hamburger').classList.add('hidden')"
  class="sticky z-[200] top-0 border-gray-200 bg-white/20 backdrop-blur-md backdrop-opacity-60 dark:bg-gray-900"
>
  <div
    class="mx-auto flex max-w-screen-xl flex-wrap items-center justify-between p-4 backdrop:blur-sm"
  >
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img
        src="{% static 'img/favicon.png' %}"
        class="h-8"
        alt="Rekomendasi Buku"
      />
      <span
        class="self-center whitespace-nowrap text-sm font-semibold md:text-xl dark:text-white"
        >Rekomendasi Buku</span
      >
    </a>
    <button
      @click="document.querySelector('.hamburger').classList.toggle('hidden')"
      data-collapse-toggle="navbar-default"
      type="button"
      class="inline-flex h-10 w-10 items-center justify-center rounded-lg p-2 text-sm text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 md:hidden dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
      aria-controls="navbar-default"
      aria-expanded="false"
    >
      <span class="sr-only">Open main menu</span>
      <svg
        class="h-5 w-5"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 17 14"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M1 1h15M1 7h15M1 13h15"
        />
      </svg>
    </button>
    <div
      class="hamburger hidden w-full transition delay-150 ease-in-out md:block md:w-auto"
      id="navbar-default"
    >
      <!-- prettier-ignore -->
      <ul
        class="mt-4 flex flex-col rounded-lg border border-gray-100 bg-gray-50 p-4 font-medium md:mt-0 md:flex-row md:space-x-8 md:border-0 md:bg-inherit md:p-0 rtl:space-x-reverse dark:border-gray-700 dark:bg-gray-800 md:dark:bg-gray-900"
      >
        {% with request.resolver_match.url_name as url_name %}
        
        <li>
          <a
            href="{% url 'daftar-buku' %}"
            class="{% if url_name == 'daftar-buku' %}text-white md:text-blue-700 bg-blue-700{% else %} dark:text-white text-gray-900 {% endif %} block rounded  px-3 py-2 md:bg-transparent md:p-0 "
            aria-current="page"
            >Home</a
          >
        </li>

        <li>
          <a
            href="{% url 'rekomendasi-buku' %}"
            class="{% if url_name == 'rekomendasi-buku' %}text-white md:text-blue-700 bg-blue-700{% else %} dark:text-white text-gray-900 {% endif %} block rounded  px-3 py-2 md:bg-transparent md:p-0 "
            >Rekomendasi Buku</a
          >
        </li>
        <li>
          <a
            href="{% url "ratting-buku" %}"
            class="{% if url_name == 'ratting-buku' %}text-white md:text-blue-700 bg-blue-700{% else %} dark:text-white text-gray-900 {% endif %} block rounded  px-3 py-2 md:bg-transparent md:p-0 "
            >Buku Ratting tinggi</a
          >
        </li>
        
        <li>
          <a
            href="/admin"
            class="{% if url_name == 'admin' %}text-white md:text-blue-700 bg-blue-700{% else %} dark:text-white text-gray-900 {% endif %} block rounded  px-3 py-2 md:bg-transparent md:p-0 "
            >Admin</a
          >
        </li>
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>

templates/search.html
<form class="flex items-center" action="{% url "search-buku" %}">
    <label for="simple-search" class="sr-only">Search</label>
    <div class="relative w-full">
      <div
        class="pointer-events-none absolute inset-y-0 start-0 flex items-center ps-3"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-4 w-4 text-gray-500 dark:text-gray-400"
          viewBox="0 0 256 256"
        >
          <g fill="currentColor">
            <path
              d="M208 32v160H72a24 24 0 0 0-24 24V56a24 24 0 0 1 24-24Z"
              opacity=".2"
            />
            <path
              d="M208 24H72a32 32 0 0 0-32 32v168a8 8 0 0 0 8 8h144a8 8 0 0 0 0-16H56a16 16 0 0 1 16-16h136a8 8 0 0 0 8-8V32a8 8 0 0 0-8-8m-8 160H72a31.82 31.82 0 0 0-16 4.29V56a16 16 0 0 1 16-16h128Z"
            />
          </g>
        </svg>
      </div>
      <input
        type="text"
        id="simple-search"
        class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 ps-10 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
        placeholder="Search book name..."
        name="q" 
        required
      />
    </div>
    <button
      type="submit"
      class="ms-2 rounded-lg border border-blue-700 bg-blue-700 p-2.5 text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
    >
      <svg
        class="h-4 w-4"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 20 20"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
        />
      </svg>
      <span class="sr-only">Search</span>
    </button>
  </form>